### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jxzhn** [AsensioL/TreePrinter#2]
It's not a good idea to have `getChildrenFunction()` and `getStringFunction()` return a reference.

In most cases I have to create the variable to return just in these functions, but returning a reference of a local variable is risky. ( After function call, the stack space of a function would be released, so the memory of its local variable should not be used , because it could be covered by future content. )

It 's also not good to return reference of variable whose memory is allocated by `new`, because its `delete` is not promised, and without a expected `delete` it can cause a memory leak problem.

So a pass-by-value return is necessary.

By the way, there are memory leak problems in your code here: (Line 184-189 in BTNode.tpp)
```c++
		// Add layers to the levels if it is not deep enough
		while (levels.size() <= nd->_depth)
		{
			levels.push_back(new std::list<BTNode *>());
		}
		levels[nd->_depth]->push_back(nd);
```
These memory allocated by `new` should be deleted in destructor `~BTNode()`.

Any way, your code help me save my time a lot~ lol

**Comment by AsensioL** [comment]
Wow, thank you so much for the feedback. It is the first time someone replies to my code in Github, and I am really excited about it.

> In most cases I have to create the variable to return just in these functions, but returning a reference of a local variable is risky
I created the code thinking of trees where the output of those functions was stored in the class itself, so returning it by reference was OK.
Returning by value could be a little slower, but I guess it would cover more cases, and allow for greater flexibility.

**Action**: I will update the `childrenGetterFcn` and `dataGetterFcn` function typedefs to expect return-by-value functions. And also, update the Examples

**Comment by AsensioL** [comment]
> By the way, there are memory leak problems in your code here: (Line 184-189 in BTNode.tpp)

The memory allocated in `groupNodesByDepth` was deleted at the end of its caller function `printTree` in the clean up section.
However, this may not be a safe delete, and the fact that the memory is allocated/deallocated in different places looks bad. I am going to switch to raw pointers to smart pointers.

**Comment by AsensioL** [comment]
I have done a few changes, let me know what you think.

**Comment by jxzhn** [comment]
The changes are great.
And sorry for posting a wrong code snippet, it seems that the memory-leak causing code is here: (Line 64-70 in BTNode.tpp)
```c++
	// Create new list of nodes, imitating the structure of the passed node
	std::list<T *> ls = getChildren();
	for (auto * child: ls)
	{
		_children.push_back(new BTNode(child));
	}
```

**Comment by AsensioL** [comment]
Both snippets were actual leaks. No need to apologize.
I ran Valgrind on the examples this times, and there should be no leaks anymore.
I used more smart pointers for the allocation of nodes in the copied tree, and also fixed the examples (they didn't release the created nodes).
Thank you for your feedback!

**Comment by AsensioL** [comment]
Unless you (or anyone else) leaves any comments, I'll just merge the code to the main branch

**Comment by jxzhn** [comment]
Okay, i'll close this issue then.
